### PR TITLE
(feat) Facebook Login Button

### PR DESCRIPTION
**Pull request by misteryeo**
- Implement Facebook SDK
- Implement Facebook Login button on Login page. Expected behaviour: Ask user to login to their Facebook and successfully 'log them in'

### CODE REVIEW

**Comment by misteryeo** [comment]
@dshelters @dbrodie122 The button works! 👍

**Comment by dbrodie122** [comment]
It works, two things for next steps:
1) Make sure to take the app out of development mode or to add us to the app on facebook so that we can log in.
2) Doesn't it come with an official facebook button?

**Comment by misteryeo** [comment]
@dbrodie122 
1. You've all been added as Admins on Facebook.
2. The official button was running some errors so decided to leave it until styling.

**Comment by misteryeo** [comment]
In my attempts to fix merge conflicts for the button, I've also pushed up the latest code which includes initial Facebook OAuth in preparation for Facebook Messenger Link Sharing. Let me know if there's any issues - otherwise we can merge this first and I'll work on the link sharing separately as originally intended! @jefQuery @dbrodie122 @dshelters

**Pull request merged**
